spring:
#    sleuth:
#      sampler:
#         percentage:  1
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    br.com.eng.vvs: DEBUG
