spring:
#    sleuth:
#      sampler:
#         percentage:  1
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
<<<<<<< HEAD
    br.com.eng.vvs: DEBUG
=======
    com.thoughtmechanix: DEBUG
    br.com.eng: DEBUG
>>>>>>> 07df8fd8603b7fe270777dbca3a75980d1931a08
